site_name: Ubuntu2Go
theme: readthedocs
pages:
- Home: index.md
- Software Installation:
    - Cuda: software/cuda.md
    - Tensorflow: software/tensorflow.md
- Linux Command:
    - free: command/free.md
- Windows:
    - Wine: windows/wine.md 